Customizable Crispness menu background.
fabiangreffrath/crispy-doom pull request #777
Opened 2021-11-06 18:52 UTC by NeuralStunner

Palette changes can make the Crispness menu background look quite strange. E.G. Back to Saturn X, which replaces several of the browns with new shades:
<img src="https://i.imgur.com/e7gVJgw.png" />
A palette-correct version can be provided by a PWAD autoload to cover these cases, or mods with changed palettes can include the replacement themselves. Any 64x64 flat will do:
<img src="https://i.imgur.com/Dcq1ajW.png" />
(>64 row flats like Heretic/Hexen use should also be fine, we only care about the first 64.)

2021-11-06 18:55 UTC, fabiangreffrath requested changes

2021-11-06 18:55 UTC, fabiangreffrath commented on src/doom/m_menu.c
> +    const byte *src = crispness_background;
Nice idea, but please keep indentation intact.

2021-11-06 19:18 UTC, fabiangreffrath commented
You can't have mixed declarations and code, and the indentation is still messed up. Does your editor allow to display whitespace chars?

2021-11-06 19:30 UTC, NeuralStunner commented
It does, everything I've added should be 4x space. I only re-indented this other line because it was a change otherwise.

The only warning mingw gives me is for `pixel_t *dest;` which I haven't modified.

2021-11-06 19:40 UTC, fabiangreffrath commented
On this page you'll see what's wrong with the indentation. 

And you must have all declarations first and then the actual code.

2021-11-06 19:55 UTC, NeuralStunner commented
Will \t (as the surrounding code) be fine?

> And you must have all declarations first and then the actual code.

Realized this shortly after. I guess JavaScript has been a terrible influence on me. :P

2021-11-06 20:07 UTC, fabiangreffrath commented
Now it's perfect, thank you!

2021-11-06 20:07 UTC, merged

2021-11-18 17:24 UTC, fragglet commented
Just my 2 cents: I think you might have leaped straight to implementing a solution without pausing to consider the possible options first. I also note that this doesn't really solve the problem, it just dumps the problem onto the user and provides a feature they can use to fix it themselves.

An alternative solution here would be to do the palette conversion inside Crispy itself. Store the background as a set of RGB values (instead of palette indexed) and before you draw the background, translate RGB into whatever palette you're using for the particular set of WADs you're using. Then the background will always look correct.

2021-11-19 08:37 UTC, fabiangreffrath commented
You are right, this would have been a more elegant solution. @NeuralStunner would you like to take a try on this?