Implement mouse smoothing when running uncapped
fabiangreffrath/crispy-doom pull request #848
Opened 2022-03-02 14:22 UTC by mikeday0

As discussed here: [https://www.doomworld.com/forum/topic/127475-sdl2-v-sync-and-mouse-movement/](url)

The idea behind my fix is to adjust each mouse read in proportion to how late we are sampling the mouse, and then to add the excess to the next tic's mouse values. It is essentially linear interpolation for the mouse movement.

I had to move the `fractionaltic` calculation to `NetUpdate` in order for it to be recent enough to be effective for this correction. Otherwise I need to get a local value in the `SmoothMouse` function. I think the main reason is that `NET_SV_Run` takes a not insignificant amount of time, and you can end up rolling over to the new tic while running that function. In that case `fractionaltic` might be some high value around 0.9.

2022-03-04 02:33 UTC, mikeday0 commented
I think moving the fractionaltic calculation is a no-go. Doing so resulted in occasional visual glitches where you'd see flashes of sprites for a frame.

2022-03-09 07:38 UTC, fabiangreffrath requested changes
Thank you very much (again!) for this contribution and sorry for the late review!

2022-03-09 07:38 UTC, fabiangreffrath commented on src/i_input.c
> +    fractic = (int64_t)I_GetTimeMS() * TICRATE % 1000 * FRACUNIT / 1000;
Could you please factor this out into a helper function as we have done here?

https://github.com/fabiangreffrath/woof/blob/b28aee2679692111c14e9c65f81a8a1054fb2c17/Source/i_system.c#L118

2022-03-10 07:02 UTC, merged

2022-03-10 07:02 UTC, fabiangreffrath commented
Thank you!